### PR TITLE
chore: AOC cleanup

### PR DESCRIPTION
**Pull request by keshavbhatt**
update all conf files to the latest from mailbox/store with AOC cleanup

### CODE REVIEW

**Comment by frisonisland** [comment]
Hey @keshavbhatt just a question: Is the [attrs.xml ](https://github.com/Zextras/carbonio-ldap-utilities/blob/main/conf/attrs/attrs.xml)file in this repo relevant?
Asking because another PR we have about IMAPD removal has some attributes that may be change here also. 
Also I don't think in the past we ever changed this file while updating attributes in other repos.

**Comment by keshavbhatt** [comment]
> Hey @keshavbhatt just a question: Is the [attrs.xml ](https://github.com/Zextras/carbonio-ldap-utilities/blob/main/conf/attrs/attrs.xml)file in this repo relevant? Asking because another PR we have about IMAPD removal has some attributes that may be change here also. Also I don't think in the past we ever changed this file while updating attributes in other repos.
 
No the file has no references, i did not tried to remove it. The one in LdapPatch make sense, but i dont know if we will utilize it.
I will run a build to confirm if removal make any impact during build.

**Comment by frisonisland** [comment]
> > Hey @keshavbhatt just a question: Is the [attrs.xml ](https://github.com/Zextras/carbonio-ldap-utilities/blob/main/conf/attrs/attrs.xml)file in this repo relevant? Asking because another PR we have about IMAPD removal has some attributes that may be change here also. Also I don't think in the past we ever changed this file while updating attributes in other repos.
> 
> No the file has no references, i did not tried to remove it. The one in LdapPatch make sense, but i dont know if we will utilize it. I will run a build to confirm if removal make any impact during build.

Ok thanks, no need to remove it right now IMO, but its nice if we acknowledge it is not needed anymore, so in future we can remove it in a dedicated PR maybe (same for other repos redundancy).
What if we put a comment saying that the file is deprecated?

**Comment by keshavbhatt** [comment]
> I will run a build to confirm if removal make any impact during build.

The removal of the conf/  has no effect on the build, nevertheless, the implications on runtime must be investigated.

**Review by frisonisland — APPROVED** [review]

**Pull request merged**
