### PR TITLE
feat: [CO-568] migration for argon2 support

### PR DESCRIPTION
**Pull request by frisonisland**
Adds perl migration file to enable argon2 module and password algorithm.

### CODE REVIEW

**Comment by keshavbhatt** [comment]
Changes looks good to me, I am just wondering how this migration will affect existing users whose password are stored as SSHA512 hash. Can you provide this info in description for future references?

**Comment by frisonisland** [comment]
> Changes looks good to me, I am just wondering how this migration will affect existing users whose password are stored as SSHA512 hash. Can you provide this info in description for future references?

Thanks Keshav, after changing to ARGON2 existing users will still have SSHA512 password. Only after they change it you will see it is stored with ARGON2 algorithm. Also authentication in ARGON2 works, but I will test the mixed scenario thoroughly

**Review by keshavbhatt — APPROVED** [review]

**Review by Polpetta — APPROVED** [review]
I trust your abilities with Perl man :wink:

**Comment by frisonisland** [comment]
> I trust your abilities with Perl man wink

Thanks, I trust this: https://github.com/Zextras/carbonio-ldap-utilities/blob/main/src/ldap/migration/migrate20140728-AddSSHA512.pl :laughing: 
Jokes aside it follows the same principle and it was tested locally.

**Pull request merged**
